### ISSUE TITLE
About Me bo'limining, About Me degan sarlavhasi h1 element orqalik yozib hatolikka yo'l qo'yilgan, saytning sarlavhasi uchun h1, bo'limning sarlavhasi uchun h2 dan foydalanish kerak. About Me ni ham h2 elementi orqalik berish kerak.

### ISSUE THREAD

**Issue by NodirXon0609** [MIRZOULUGBEK9008/minimalist-selfmade#1]
https://github.com/MIRZOULUGBEK9008/minimalist-selfmade/blob/98b892541aa21d0d78c04b0f314e274d2bc302ad/index.html#L73

**Comment by MIRZOULUGBEK9008** [comment]
#fix O'zgartirildi `h1` da olganimning sababi sahifadagi barcha ma'lumotlar avtor haqida borayotgani uchun `h1` da olgan edim. :)
