### ISSUE TITLE
" Manage " bo'limining "Manage" deb nomlangan sarlavhasi h3 elementi orqalik berilib hatolikka yo'l qo'yilgan, bo'limning sarlavhasi h2 elementi orqalik berilishi kerak.

### ISSUE THREAD

**Issue by NodirXon0609** [MIRZOULUGBEK9008/minimalist-selfmade#2]
https://github.com/MIRZOULUGBEK9008/minimalist-selfmade/blob/98b892541aa21d0d78c04b0f314e274d2bc302ad/portfolio.html#L60
Sarlavhaning saytdagi joylashuvi: https://prnt.sc/RCigQpmxziVo

**Comment by MIRZOULUGBEK9008** [comment]
> https://github.com/MIRZOULUGBEK9008/minimalist-selfmade/blob/98b892541aa21d0d78c04b0f314e274d2bc302ad/portfolio.html#L60
> 
> 
> Sarlavhaning saytdagi joylashuvi: https://prnt.sc/RCigQpmxziVo

Saytning ushbu sahifasida `h1` hamda `h2` sarlavha darajalari `.visually-hidden` bilan berilib bu bo'lim nomlari `h3` da ketaveradi.

isbot: https://t.me/c/1726803916/4525
Minimalist maketining muhokamasida ko'rib chiqganmiz :) 

#fix
