### ISSUE TITLE
Portfolio sahifasining Insure bo'limidagi matn maketdagidan farq qilyapdi. Maketdagi va saytdagi holatlarning quyida linklari keltirilgan.

### ISSUE THREAD

**Issue by NodirXon0609** [MIRZOULUGBEK9008/minimalist-selfmade#3]
Saytdagi holat: https://prnt.sc/9H6iMWaf29m8
Maketdagi holat: https://prnt.sc/WjSAs9yN79wh

**Comment by MIRZOULUGBEK9008** [comment]
Barcha stillar figma bo'yicha berilgan, lekin bilmadim nega bunaqa e'tibor beringda aynan Insure da shunaqa.
