### ISSUE TITLE
Contact sahifasini "SEND  MESSAGE" buttonining rangi maketdagidan farq qilyapdi. Quyida saytdagi va maketdagi holatlar keltirilgan.

### ISSUE THREAD

**Issue by NodirXon0609** [MIRZOULUGBEK9008/minimalist-selfmade#4]
Saytdagi holat: https://prnt.sc/LU3QUzGyq-2M
Maketdagi holat: ![image](https://user-images.githubusercontent.com/99398673/180172455-4629f8c7-4182-48af-b34a-a2f63ebe9988.png)

**Comment by MIRZOULUGBEK9008** [comment]
#fix
